### PR TITLE
Updates for Flask 2.3+

### PR DESCRIPTION
**Pull request by filak**

### CODE REVIEW

**Comment by tarsil** [comment]
Nice one 🙂

**Comment by tarsil** [comment]
I will take care of the new release during the day. I want to also make some changes into the CI. Thank you @filak

**Comment by tarsil** [comment]
@filak apologies but today I didn't have the time but it's in my priority 🙂

**Comment by filak** [comment]
Thanks! Are you going to update the package at PyPI ?

**Comment by tarsil** [comment]
> Thanks! Are you going to update the package at PyPI ?

Yes, that is the plan. At least next week I will. I want to add some extras in CI and automate the process in the same way we do the remaining opensource. This was one of our first packages a few years ago.

**Comment by tarsil** [comment]
@filak thank you for your collaboration and PR. The release 0.5.0 is now published :)

**Pull request merged**
